openapi: 3.0.0
info:
  title: book-my-show
  version: 1.0.0
servers:
  - url: http://localhost:3000
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
tags:
  - name: auth
  - name: role
  - name: user
  - name: city
  - name: theater
  - name: movie
  - name: show
  - name: booking
  - name: transaction
paths:
  /api/auth/register:
    post:
      tags:
        - auth
      summary: register-user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Akshay
                email: akshay@mailinator.com
                password: Akshay@1234
                phone: '9873456781'
                roles:
                  - Theater Owner
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/auth/send-otp:
    post:
      tags:
        - auth
      summary: send-otp
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: yash@mailinator.com
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/auth/verify-otp:
    post:
      tags:
        - auth
      summary: verify-otp
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: |-
                {
                    "email":"yash4@mailinator.com"
                    "otp":"327315"
                }
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/auth/login:
    post:
      tags:
        - auth
      summary: login-user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: adityasinghrajawat393@gmail.com
                password: Aditya@1234
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/auth/logout:
    delete:
      tags:
        - auth
      summary: logout-user
      parameters:
        - name: authorization
          in: header
          schema:
            type: string
          example: >-
            bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNTQ3YzM4YzktNDU0Yy00N2JkLWJmMGUtYWEzMmViMjBlMmMxIiwicm9sZXMiOlsiQ3VzdG9tZXIiXSwic2VsZWN0ZWRSb2xlIjoiQ3VzdG9tZXIiLCJpYXQiOjE3MzIxODM5ODEsImV4cCI6MTczMjI3MDM4MX0.d1L_5C1EzsjVt3-bcvYSMUAsTFSebY98LHf5VyzILx
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/roles:
    post:
      tags:
        - role
      summary: create-role
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Content Creator
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - role
      summary: get all roles
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/roles/{id}:
    get:
      tags:
        - role
      summary: get single role
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: fdf791b0-40cc-4a2b-93ae-75f42dc4bbbf
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - role
      summary: update role
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: njdfhuvjndf
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 40a4440b-3112-4306-b8c1-bf145e488df2
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - role
      summary: delete role
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 40a4440b-3112-4306-b8c1-bf145e488df2
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/users/me:
    get:
      tags:
        - user
      summary: get current user
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/users:
    get:
      tags:
        - user
      summary: get all user(Admin only)
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOWZkY2FlNTUtNTliMC00NDZhLWI4YzctNTI0NDhjYjUxNDM4Iiwicm9sZXMiOlsiQWRtaW4iXSwic2VsZWN0ZWRSb2xlIjoiQWRtaW4iLCJpYXQiOjE3MzIxODQ1NDAsImV4cCI6MTczMjI3MDk0MH0.eCQeHmwqPo7nb-X0EBHDwCCaOU_gM4FinYvCv8p4ieU
        - name: page
          in: query
          schema:
            type: integer
          example: '1'
        - name: limit
          in: query
          schema:
            type: integer
          example: '5'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/users/{id}:
    get:
      tags:
        - user
      summary: get user by id(Admin and user themselves)
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOWZkY2FlNTUtNTliMC00NDZhLWI4YzctNTI0NDhjYjUxNDM4Iiwicm9sZXMiOlsiQWRtaW4iXSwic2VsZWN0ZWRSb2xlIjoiQWRtaW4iLCJpYXQiOjE3MzIxODQ1NDAsImV4cCI6MTczMjI3MDk0MH0.eCQeHmwqPo7nb-X0EBHDwCCaOU_gM4FinYvCv8p4ieU
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 67b07a8f-88cd-45df-b811-8daa44fff2ef
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - user
      summary: update user by id(Admin and user themselves)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: meena
                phone: '8765434522'
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOWZkY2FlNTUtNTliMC00NDZhLWI4YzctNTI0NDhjYjUxNDM4Iiwicm9sZXMiOlsiQWRtaW4iXSwic2VsZWN0ZWRSb2xlIjoiQWRtaW4iLCJpYXQiOjE3MzIxODQ1NDAsImV4cCI6MTczMjI3MDk0MH0.eCQeHmwqPo7nb-X0EBHDwCCaOU_gM4FinYvCv8p4ieU
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 67b07a8f-88cd-45df-b811-8daa44fff2ef
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - user
      summary: delete user by id(Admin or and user themselves)
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOWZkY2FlNTUtNTliMC00NDZhLWI4YzctNTI0NDhjYjUxNDM4Iiwicm9sZXMiOlsiQWRtaW4iXSwic2VsZWN0ZWRSb2xlIjoiQWRtaW4iLCJpYXQiOjE3MzIxODQ1NDAsImV4cCI6MTczMjI3MDk0MH0.eCQeHmwqPo7nb-X0EBHDwCCaOU_gM4FinYvCv8p4ieU
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 67b07a8f-88cd-45df-b811-8daa44fff2ef
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/users/{id}/bookings:
    get:
      tags:
        - user
      summary: get user bookings(Admin only)
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOWZkY2FlNTUtNTliMC00NDZhLWI4YzctNTI0NDhjYjUxNDM4Iiwicm9sZXMiOlsiQWRtaW4iXSwic2VsZWN0ZWRSb2xlIjoiQWRtaW4iLCJpYXQiOjE3MzIxODQ1NDAsImV4cCI6MTczMjI3MDk0MH0.eCQeHmwqPo7nb-X0EBHDwCCaOU_gM4FinYvCv8p4ieU
        - name: page
          in: query
          schema:
            type: integer
          example: '2'
        - name: limit
          in: query
          schema:
            type: integer
          example: '1'
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 9fdcae55-59b0-446a-b8c7-52448cb51438
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/users/{id}/transactions:
    get:
      tags:
        - user
      summary: get specific user all transactions
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOWZkY2FlNTUtNTliMC00NDZhLWI4YzctNTI0NDhjYjUxNDM4Iiwicm9sZXMiOlsiQWRtaW4iXSwic2VsZWN0ZWRSb2xlIjoiQWRtaW4iLCJpYXQiOjE3MzIxODQ1NDAsImV4cCI6MTczMjI3MDk0MH0.eCQeHmwqPo7nb-X0EBHDwCCaOU_gM4FinYvCv8p4ieU
        - name: page
          in: query
          schema:
            type: integer
          example: '1'
        - name: limit
          in: query
          schema:
            type: integer
          example: '1'
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: d1ecc0e2-555c-4786-9081-b44ed4584df7
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/users/reports:
    get:
      tags:
        - user
      summary: users report(Admin)
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOWZkY2FlNTUtNTliMC00NDZhLWI4YzctNTI0NDhjYjUxNDM4Iiwicm9sZXMiOlsiQWRtaW4iXSwic2VsZWN0ZWRSb2xlIjoiQWRtaW4iLCJpYXQiOjE3MzIxODQ1NDAsImV4cCI6MTczMjI3MDk0MH0.eCQeHmwqPo7nb-X0EBHDwCCaOU_gM4FinYvCv8p4ieU
        - name: page
          in: query
          schema:
            type: integer
          example: '3'
        - name: limit
          in: query
          schema:
            type: integer
          example: '5'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/cities:
    post:
      tags:
        - city
      summary: add-city(Admin only)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: goa
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOWZkY2FlNTUtNTliMC00NDZhLWI4YzctNTI0NDhjYjUxNDM4Iiwicm9sZXMiOlsiQWRtaW4iXSwic2VsZWN0ZWRSb2xlIjoiQWRtaW4iLCJpYXQiOjE3MzIxODQ1NDAsImV4cCI6MTczMjI3MDk0MH0.eCQeHmwqPo7nb-X0EBHDwCCaOU_gM4FinYvCv8p4ieU
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - city
      summary: get all cities
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOWZkY2FlNTUtNTliMC00NDZhLWI4YzctNTI0NDhjYjUxNDM4Iiwicm9sZXMiOlsiQWRtaW4iXSwic2VsZWN0ZWRSb2xlIjoiQWRtaW4iLCJpYXQiOjE3MzE5MDYxOTUsImV4cCI6MTczMTkwOTc5NX0.apyIhcbHuJMos7XjhCdijzH7KxU-AYf86z0PWEk00KI
        - name: page
          in: query
          schema:
            type: integer
          example: '2'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/cities/{id}:
    get:
      tags:
        - city
      summary: get city by id
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOWZkY2FlNTUtNTliMC00NDZhLWI4YzctNTI0NDhjYjUxNDM4Iiwicm9sZXMiOlsiQWRtaW4iXSwic2VsZWN0ZWRSb2xlIjoiQWRtaW4iLCJpYXQiOjE3MzE5MDYxOTUsImV4cCI6MTczMTkwOTc5NX0.apyIhcbHuJMos7XjhCdijzH7KxU-AYf86z0PWEk00KI
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 839d23d5-a610-4925-a07e-2036e405dc27
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - city
      summary: update city by id (admin only)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Patiala
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOWZkY2FlNTUtNTliMC00NDZhLWI4YzctNTI0NDhjYjUxNDM4Iiwicm9sZXMiOlsiQWRtaW4iXSwic2VsZWN0ZWRSb2xlIjoiQWRtaW4iLCJpYXQiOjE3MzIxODQ1NDAsImV4cCI6MTczMjI3MDk0MH0.eCQeHmwqPo7nb-X0EBHDwCCaOU_gM4FinYvCv8p4ieU
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 6ca574bd-2b90-4a36-bf66-ac37cec1d2a6
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - city
      summary: delete city by id (admin only)
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOWZkY2FlNTUtNTliMC00NDZhLWI4YzctNTI0NDhjYjUxNDM4Iiwicm9sZXMiOlsiQWRtaW4iXSwic2VsZWN0ZWRSb2xlIjoiQWRtaW4iLCJpYXQiOjE3MzIxODQ1NDAsImV4cCI6MTczMjI3MDk0MH0.eCQeHmwqPo7nb-X0EBHDwCCaOU_gM4FinYvCv8p4ieU
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: bfd70ecf-ae6c-4abe-a3ce-54659e5e15ec
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/cities/reports:
    get:
      tags:
        - city
      summary: city report(Admin)
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOWZkY2FlNTUtNTliMC00NDZhLWI4YzctNTI0NDhjYjUxNDM4Iiwicm9sZXMiOlsiQWRtaW4iXSwic2VsZWN0ZWRSb2xlIjoiQWRtaW4iLCJpYXQiOjE3MzIxODQ1NDAsImV4cCI6MTczMjI3MDk0MH0.eCQeHmwqPo7nb-X0EBHDwCCaOU_gM4FinYvCv8p4ieU
        - name: city
          in: query
          schema:
            type: string
          example: alwar
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/cities/{id}/theaters:
    get:
      tags:
        - city
      summary: Get all theatres(Admin)
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            B
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOWZkY2FlNTUtNTliMC00NDZhLWI4YzctNTI0NDhjYjUxNDM4Iiwicm9sZXMiOlsiQWRtaW4iXSwic2VsZWN0ZWRSb2xlIjoiQWRtaW4iLCJpYXQiOjE3MzIxODQ1NDAsImV4cCI6MTczMjI3MDk0MH0.eCQeHmwqPo7nb-X0EBHDwCCaOU_gM4FinYvCv8p4ieU
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 944b682e-9434-4346-b1a7-cd1a7aa43d89
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/theaters:
    post:
      tags:
        - theater
      summary: add-theater(admin only)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                cityId: ecd0b538-485a-487e-ab9f-829fee936e60
                name: Most Wanted Theater
                address: justin pune
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOWZkY2FlNTUtNTliMC00NDZhLWI4YzctNTI0NDhjYjUxNDM4Iiwicm9sZXMiOlsiQWRtaW4iXSwic2VsZWN0ZWRSb2xlIjoiQWRtaW4iLCJpYXQiOjE3MzIxODQ1NDAsImV4cCI6MTczMjI3MDk0MH0.eCQeHmwqPo7nb-X0EBHDwCCaOU_gM4FinYvCv8p4ieU
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - theater
      summary: get all theaters (admin only)
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOWZkY2FlNTUtNTliMC00NDZhLWI4YzctNTI0NDhjYjUxNDM4Iiwicm9sZXMiOlsiQWRtaW4iXSwic2VsZWN0ZWRSb2xlIjoiQWRtaW4iLCJpYXQiOjE3MzIxODQ1NDAsImV4cCI6MTczMjI3MDk0MH0.eCQeHmwqPo7nb-X0EBHDwCCaOU_gM4FinYvCv8p4ieU
        - name: page
          in: query
          schema:
            type: integer
          example: '2'
        - name: limit
          in: query
          schema:
            type: integer
          example: '5'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/theaters/{id}:
    get:
      tags:
        - theater
      summary: get theater by id(admin and theater owner only)
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOWZkY2FlNTUtNTliMC00NDZhLWI4YzctNTI0NDhjYjUxNDM4Iiwicm9sZXMiOlsiQWRtaW4iXSwic2VsZWN0ZWRSb2xlIjoiQWRtaW4iLCJpYXQiOjE3MzIxODQ1NDAsImV4cCI6MTczMjI3MDk0MH0.eCQeHmwqPo7nb-X0EBHDwCCaOU_gM4FinYvCv8p4ieU
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: e360e182-1c11-423d-a437-25b775c69ddc
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - theater
      summary: update theater details (Theater Owner only)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Theater Nice
                address: justin pune
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOWZkY2FlNTUtNTliMC00NDZhLWI4YzctNTI0NDhjYjUxNDM4Iiwicm9sZXMiOlsiQWRtaW4iXSwic2VsZWN0ZWRSb2xlIjoiQWRtaW4iLCJpYXQiOjE3MzIxODQ1NDAsImV4cCI6MTczMjI3MDk0MH0.eCQeHmwqPo7nb-X0EBHDwCCaOU_gM4FinYvCv8p4ieU
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: e360e182-1c11-423d-a437-25b775c69ddc
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - theater
      summary: delete theater by id(Admin and Theater Owner)
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNzg5ODljNzctYTNiMS00YmYzLWI2ODYtYTYwYjZiZDliMTcwIiwicm9sZXMiOlsiVGhlYXRlciBPd25lciJdLCJzZWxlY3RlZFJvbGUiOiJUaGVhdGVyIE93bmVyIiwiaWF0IjoxNzMyMDQzODcxLCJleHAiOjE3MzIwNDc0NzF9.WtYAITN3CtJ-H363tItww4qD7Fi63q3-r_g5adbho8Y
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: e360e182-1c11-423d-a437-25b775c69ddc
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/theaters/{id}/movies:
    get:
      tags:
        - theater
      summary: get movie of specific theater
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOWZkY2FlNTUtNTliMC00NDZhLWI4YzctNTI0NDhjYjUxNDM4Iiwicm9sZXMiOlsiQWRtaW4iXSwic2VsZWN0ZWRSb2xlIjoiQWRtaW4iLCJpYXQiOjE3MzIxODQ1NDAsImV4cCI6MTczMjI3MDk0MH0.eCQeHmwqPo7nb-X0EBHDwCCaOU_gM4FinYvCv8p4ieU
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 6fea481f-76a1-4027-b378-78dd3f1f780a
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/theaters/reports:
    get:
      tags:
        - theater
      summary: theater report(Admin)
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOWZkY2FlNTUtNTliMC00NDZhLWI4YzctNTI0NDhjYjUxNDM4Iiwicm9sZXMiOlsiQWRtaW4iXSwic2VsZWN0ZWRSb2xlIjoiQWRtaW4iLCJpYXQiOjE3MzIxODQ1NDAsImV4cCI6MTczMjI3MDk0MH0.eCQeHmwqPo7nb-X0EBHDwCCaOU_gM4FinYvCv8p4ieU
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/movies:
    post:
      tags:
        - movie
      summary: post-movie(Theater Owner)
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                poster:
                  type: string
                  format: binary
                trailer:
                  type: string
                  format: binary
                name:
                  type: string
                  example: Jailer
                summary:
                  type: string
                  example: Romantic
                releaseDate:
                  type: string
                  example: 01-04-2023
                genre:
                  type: string
                  example: Romance
                language:
                  type: string
                  example: Hindi
                castMemberList[]:
                  type: string
                  example: Renate Reinsve
                theaterIds[]:
                  type: string
                  example: 4309e1c7-dc06-47f0-b7dc-5cfa318ae74a
                category:
                  type: string
                  example: A
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNDczNzhhNDMtNmI3Yi00MGVjLTk3MjktN2M4MGQxZjI3OTE3Iiwicm9sZXMiOlsiVGhlYXRlciBPd25lciIsIkN1c3RvbWVyIl0sInNlbGVjdGVkUm9sZSI6IlRoZWF0ZXIgT3duZXIiLCJpYXQiOjE3MzIxNjUyNTMsImV4cCI6MTczMjE2ODg1M30.oXc9UtK6ukD0c55ouW7mlTbt8Je35M2bsMAIcJKtbWc
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - movie
      summary: get all movies
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNDczNzhhNDMtNmI3Yi00MGVjLTk3MjktN2M4MGQxZjI3OTE3Iiwicm9sZXMiOlsiVGhlYXRlciBPd25lciIsIkN1c3RvbWVyIl0sInNlbGVjdGVkUm9sZSI6IlRoZWF0ZXIgT3duZXIiLCJpYXQiOjE3MzIxOTMzNTMsImV4cCI6MTczMjI3OTc1M30.FeerBXuwzFntAYsNlD2bDL26NmGqjzqbXDnJ_73wrOE
        - name: category
          in: query
          schema:
            type: string
          example: A
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/movies/{id}:
    get:
      tags:
        - movie
      summary: get movie by id
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            B
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNDczNzhhNDMtNmI3Yi00MGVjLTk3MjktN2M4MGQxZjI3OTE3Iiwicm9sZXMiOlsiVGhlYXRlciBPd25lciIsIkN1c3RvbWVyIl0sInNlbGVjdGVkUm9sZSI6IlRoZWF0ZXIgT3duZXIiLCJpYXQiOjE3MzIxOTMzNTMsImV4cCI6MTczMjI3OTc1M30.FeerBXuwzFntAYsNlD2bDL26NmGqjzqbXDnJ_73wrOE
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: e4656986-bf1c-40de-8e34-666cc8919441
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - movie
      summary: update movie by id (Theater Owner  and admin)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Singham Again
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNDczNzhhNDMtNmI3Yi00MGVjLTk3MjktN2M4MGQxZjI3OTE3Iiwicm9sZXMiOlsiVGhlYXRlciBPd25lciIsIkN1c3RvbWVyIl0sInNlbGVjdGVkUm9sZSI6IlRoZWF0ZXIgT3duZXIiLCJpYXQiOjE3MzIxOTMzNTMsImV4cCI6MTczMjI3OTc1M30.FeerBXuwzFntAYsNlD2bDL26NmGqjzqbXDnJ_73wrOE
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: e4656986-bf1c-40de-8e34-666cc8919441
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - movie
      summary: delete movie by id(Admin and Theater Owner only)
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOWZkY2FlNTUtNTliMC00NDZhLWI4YzctNTI0NDhjYjUxNDM4Iiwicm9sZXMiOlsiQWRtaW4iXSwic2VsZWN0ZWRSb2xlIjoiQWRtaW4iLCJpYXQiOjE3MzE5MDc5MzQsImV4cCI6MTczMTkxMTUzNH0.nF0mHAHcMjbaAFIjVuh6uLdBSo_F2pANroDDZUwBJ08
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 0543d995-9099-400a-99c8-d4ac13d127da
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/movies/{id}/theaters:
    get:
      tags:
        - movie
      summary: get theater by movie id(Admin and Theater Owner)
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOWZkY2FlNTUtNTliMC00NDZhLWI4YzctNTI0NDhjYjUxNDM4Iiwicm9sZXMiOlsiQWRtaW4iXSwic2VsZWN0ZWRSb2xlIjoiQWRtaW4iLCJpYXQiOjE3MzIxMDA0MjIsImV4cCI6MTczMjEwNDAyMn0.MSfd6gVU7BYmVS-S1gS4HcbpPyvJNJF5wdj-HAKmn4U
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: e4656986-bf1c-40de-8e34-666cc8919441
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/movies/reports:
    get:
      tags:
        - movie
      summary: movie reoprts(Admin)
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOWZkY2FlNTUtNTliMC00NDZhLWI4YzctNTI0NDhjYjUxNDM4Iiwicm9sZXMiOlsiQWRtaW4iXSwic2VsZWN0ZWRSb2xlIjoiQWRtaW4iLCJpYXQiOjE3MzIxNzQ2MzksImV4cCI6MTczMjE3ODIzOX0.DuKqm1BEPz29CFlHo99ikeDCCGR0EOy2jUiiStVzF30
        - name: startDate
          in: query
          schema:
            type: string
          example: 01-11-2024
        - name: endDate
          in: query
          schema:
            type: string
          example: 01-12-2024
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/shows:
    post:
      tags:
        - show
      summary: add-show
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                movieId: 43d4c1e0-741f-44c8-ac78-998c2178fdce
                theaterId: a4e57883-5f30-4e00-843e-47275975e80c
                showTime: '2024-11-26 7:32:42.704+00'
                availableSeats: 220
                type: 2D
                price: 450
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNDczNzhhNDMtNmI3Yi00MGVjLTk3MjktN2M4MGQxZjI3OTE3Iiwicm9sZXMiOlsiVGhlYXRlciBPd25lciIsIkN1c3RvbWVyIl0sInNlbGVjdGVkUm9sZSI6IlRoZWF0ZXIgT3duZXIiLCJpYXQiOjE3MzIxNjkxMjIsImV4cCI6MTczMjE3MjcyMn0.8xZHMvEQL6t8dbNsrFu6qW6yMSvsNnk0JinbUYGPzdU
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - show
      summary: get all shows
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNDczNzhhNDMtNmI3Yi00MGVjLTk3MjktN2M4MGQxZjI3OTE3Iiwicm9sZXMiOlsiVGhlYXRlciBPd25lciIsIkN1c3RvbWVyIl0sInNlbGVjdGVkUm9sZSI6IlRoZWF0ZXIgT3duZXIiLCJpYXQiOjE3MzIxNjkxMjIsImV4cCI6MTczMjE3MjcyMn0.8xZHMvEQL6t8dbNsrFu6qW6yMSvsNnk0JinbUYGPzdU
        - name: page
          in: query
          schema:
            type: integer
          example: '1'
        - name: limit
          in: query
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/shows/{id}:
    get:
      tags:
        - show
      summary: get show by id
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNDczNzhhNDMtNmI3Yi00MGVjLTk3MjktN2M4MGQxZjI3OTE3Iiwicm9sZXMiOlsiVGhlYXRlciBPd25lciIsIkN1c3RvbWVyIl0sInNlbGVjdGVkUm9sZSI6IlRoZWF0ZXIgT3duZXIiLCJpYXQiOjE3MzIxNjkxMjIsImV4cCI6MTczMjE3MjcyMn0.8xZHMvEQL6t8dbNsrFu6qW6yMSvsNnk0JinbUYGPzdU
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 5199d78a-a5e4-405f-8e1e-118f8500a066
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - show
      summary: update show by id
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                type: 3D
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNDczNzhhNDMtNmI3Yi00MGVjLTk3MjktN2M4MGQxZjI3OTE3Iiwicm9sZXMiOlsiVGhlYXRlciBPd25lciIsIkN1c3RvbWVyIl0sInNlbGVjdGVkUm9sZSI6IlRoZWF0ZXIgT3duZXIiLCJpYXQiOjE3MzIxNjkxMjIsImV4cCI6MTczMjE3MjcyMn0.8xZHMvEQL6t8dbNsrFu6qW6yMSvsNnk0JinbUYGPzdU
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 5199d78a-a5e4-405f-8e1e-118f8500a066
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - show
      summary: delete show by id
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNzg5ODljNzctYTNiMS00YmYzLWI2ODYtYTYwYjZiZDliMTcwIiwicm9sZXMiOlsiVGhlYXRlciBPd25lciJdLCJzZWxlY3RlZFJvbGUiOiJUaGVhdGVyIE93bmVyIiwiaWF0IjoxNzMyMDQ1MTI1LCJleHAiOjE3MzIwNDg3MjV9.Cvfk2UgBAdhE7F8hlqTNdEoMiN2Lp1aKQ4yaA_aO66w
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 5199d78a-a5e4-405f-8e1e-118f8500a066
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/bookings:
    post:
      tags:
        - booking
      summary: create-booking
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                showId: e035abbe-885c-449d-bdf8-17276289f41e
                numberOfSeats: 55
                bookingDate: '2024-11-27T20:21:29.704Z'
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNDczNzhhNDMtNmI3Yi00MGVjLTk3MjktN2M4MGQxZjI3OTE3Iiwicm9sZXMiOlsiVGhlYXRlciBPd25lciIsIkN1c3RvbWVyIl0sInNlbGVjdGVkUm9sZSI6IlRoZWF0ZXIgT3duZXIiLCJpYXQiOjE3MzIxNjkxMjIsImV4cCI6MTczMjE3MjcyMn0.8xZHMvEQL6t8dbNsrFu6qW6yMSvsNnk0JinbUYGPzdU
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - booking
      summary: get all bookings
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNDczNzhhNDMtNmI3Yi00MGVjLTk3MjktN2M4MGQxZjI3OTE3Iiwicm9sZXMiOlsiVGhlYXRlciBPd25lciIsIkN1c3RvbWVyIl0sInNlbGVjdGVkUm9sZSI6IlRoZWF0ZXIgT3duZXIiLCJpYXQiOjE3MzIxNjkxMjIsImV4cCI6MTczMjE3MjcyMn0.8xZHMvEQL6t8dbNsrFu6qW6yMSvsNnk0JinbUYGPzdU
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/bookings/{id}:
    get:
      tags:
        - booking
      summary: get booking by id
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNDczNzhhNDMtNmI3Yi00MGVjLTk3MjktN2M4MGQxZjI3OTE3Iiwicm9sZXMiOlsiVGhlYXRlciBPd25lciIsIkN1c3RvbWVyIl0sInNlbGVjdGVkUm9sZSI6IlRoZWF0ZXIgT3duZXIiLCJpYXQiOjE3MzIxNjkxMjIsImV4cCI6MTczMjE3MjcyMn0.8xZHMvEQL6t8dbNsrFu6qW6yMSvsNnk0JinbUYGPzdU
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 442478aa-51fd-46b5-8334-85176acad72b
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - booking
      summary: update booking by id(Self only)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                bookingStatus: Canceled
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 442478aa-51fd-46b5-8334-85176acad72b
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - booking
      summary: delete booking by id
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOWZkY2FlNTUtNTliMC00NDZhLWI4YzctNTI0NDhjYjUxNDM4Iiwicm9sZXMiOlsiQWRtaW4iXSwic2VsZWN0ZWRSb2xlIjoiQWRtaW4iLCJpYXQiOjE3MzE2NzUwNDYsImV4cCI6MTczMTY3ODY0Nn0.MI5QnGOkdfVo2tnY-Uok1zoX8epBNIVyFhl7dkmdZn4
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 826a10c0-f5b4-4271-9601-639a758cf8b1
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/bookings/reports:
    get:
      tags:
        - booking
      summary: booking report (Admin)
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOWZkY2FlNTUtNTliMC00NDZhLWI4YzctNTI0NDhjYjUxNDM4Iiwicm9sZXMiOlsiQWRtaW4iXSwic2VsZWN0ZWRSb2xlIjoiQWRtaW4iLCJpYXQiOjE3MzIxNzQ2MzksImV4cCI6MTczMjE3ODIzOX0.DuKqm1BEPz29CFlHo99ikeDCCGR0EOy2jUiiStVzF30
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/transactions:
    post:
      tags:
        - transaction
      summary: create-transaction
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                bookingId: 7f779242-fc2c-4d22-a33d-1d7d6f1e6625
                userId: 47378a43-6b7b-40ec-9729-7c80d1f27917
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNzg5ODljNzctYTNiMS00YmYzLWI2ODYtYTYwYjZiZDliMTcwIiwicm9sZXMiOlsiVGhlYXRlciBPd25lciJdLCJzZWxlY3RlZFJvbGUiOiJUaGVhdGVyIE93bmVyIiwiaWF0IjoxNzMyMTczMjA2LCJleHAiOjE3MzIxNzY4MDZ9.vboaIr-uBvoiCsgYMj3_GZ9UGphAssFQ310xIT3G0I8
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - transaction
      summary: get all users transaction(Admin)
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNDczNzhhNDMtNmI3Yi00MGVjLTk3MjktN2M4MGQxZjI3OTE3Iiwicm9sZXMiOlsiVGhlYXRlciBPd25lciIsIkN1c3RvbWVyIl0sInNlbGVjdGVkUm9sZSI6IlRoZWF0ZXIgT3duZXIiLCJpYXQiOjE3MzIxNzI0MjEsImV4cCI6MTczMjE3NjAyMX0.7kvsjhzSHySTmyA8I-zB5DGDHVaYy9Ahun-R2eEYjGA
        - name: user_id
          in: query
          schema:
            type: string
          example: 47378a43-6b7b-40ec-9729-7c80d1f27917
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/transactions/{id}:
    get:
      tags:
        - transaction
      summary: get transaction by id
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNDczNzhhNDMtNmI3Yi00MGVjLTk3MjktN2M4MGQxZjI3OTE3Iiwicm9sZXMiOlsiVGhlYXRlciBPd25lciIsIkN1c3RvbWVyIl0sInNlbGVjdGVkUm9sZSI6IlRoZWF0ZXIgT3duZXIiLCJpYXQiOjE3MzIxNzI0MjEsImV4cCI6MTczMjE3NjAyMX0.7kvsjhzSHySTmyA8I-zB5DGDHVaYy9Ahun-R2eEYjGA
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: c3d4fe7c-19ea-4535-a851-813eb183ddae
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - transaction
      summary: delete transaction by id
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: fba1fbb1-9f23-4fb0-a56a-f8531966ed35
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
